# Generated by Django 4.0.1 on 2022-01-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('tag', models.CharField(max_length=100, verbose_name='Теги')),
                ('pub_date_post', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-pub_date_post'],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.post')),
            ],
            options={
                'verbose_name': 'Лайки',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Автор')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('pub_date_comment', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.post')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-pub_date_comment'],
            },
        ),
    ]
